name: sim 
root: ~/roboracer_ws

windows:
  - simulator:
      layout: main-vertical
      panes:
        - 
        - DISPLAY="${DISPLAY:-:1}" ./simulator/simulator/build/linux/sim.x86_64 --scene circuit_launch --port 9999 --host 127.0.0.1 -logfile - 
        -
          - ./container shell
          - ros2 run av_sim simulator_bridge
        -
          - ./container shell
          - ros2 run ut_automata gui --windowed
        -
          - ./container shell
          - ros2 run ut_automata joystick
