name: record_map
root: ~/roboracer_ws

windows:
  - simulator:
      layout: main-vertical
      panes:
        - 
        - ros2 launch av_navigation slam.launch.py
        - ros2 launch ut_automata hokuyo_10lx.launch.py
        - ros2 run ut_automata vesc_driver
        - ros2 run ut_automata joystick
        - ros2 launch av_description description.launch.py
        - ros2 run ut_automata gui
        - vnc
        - sleep 10; DISPLAY=:9 rviz2 -d rviz2/navstack.rviz