name: record_map
root: ~/roboracer_ws

windows:
  - simulator:
      layout: main-vertical
      panes:
        - 
        - ros2 launch slam_toolbox online_async_launch.py slam_params_file:=params/slam_toolbox/roboracer.yaml use_sim_time:=false
        - ros2 launch ut_automata hokuyo_10lx.launch.py
        - ros2 run ut_automata vesc_driver
        - ros2 run ut_automata joystick
        - ros2 launch roboracer_description description.launch.py
        - ros2 launch foxglove_bridge foxglove_bridge_launch.xml
        - ros2 run ut_automata gui