PACKAGE_NAME="hid-playstation"
PACKAGE_VERSION="6.8"
BUILT_MODULE_NAME[0]="hid-playstation"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make all KDIR=/lib/modules/${kernelver}/build"
AUTOINSTALL="yes"
