name: teleop
root: ~/roboracer_ws

windows:
  - simulator:
      layout: main-vertical
      panes:
        - 
        - ros2 launch mpu6050driver mpu6050driver_launch.py
        - ros2 run orin_rp2_csi mono_processor --ros-args -p width:=320 -p height:=240 -p framerate:=30 -p display_mode:="none"
        - ros2 launch ut_automata hokuyo_10lx.launch.py
        - ros2 run ut_automata vesc_driver
        - ros2 run ut_automata joystick
        - ros2 launch roboracer_description description.launch.py
        - ros2 launch foxglove_bridge foxglove_bridge_launch.xml
        - ros2 run ut_automata gui